name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-android:
    runs-on: ubuntu-22.04 # Use Ubuntu 22.04 for immediate execution
    timeout-minutes: 90

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Use Python 3.10 for Ubuntu 22.04 compatibility

      - name: Cache buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository universe -y
          sudo apt-get update

          # Install core build dependencies first
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-11-jdk \
            python3-pip \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev \
            build-essential \
            wget \
            curl \
            libxml2-dev \
            libxslt-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            libgif-dev
            
          # Install SDL2 and multimedia packages
          sudo apt-get install -y \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev
            
          # Install FFmpeg packages
          sudo apt-get install -y \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev
            
          # Install GStreamer with proper dependencies
          sudo apt-get install -y \
            libunwind-dev \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-good1.0-dev
            
          # Install graphics and GUI packages
          sudo apt-get install -y \
            libgirepository1.0-dev \
            libcairo2-dev \
            python3-gi \
            python3-gi-cairo
            
          # Install audio and input packages
          sudo apt-get install -y \
            libasound2-dev \
            libpulse-dev \
            libudev-dev \
            libinput-dev \
            libts-dev
            
          # Install X11 and OpenGL packages
          sudo apt-get install -y \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libxinerama-dev \
            libxxf86vm-dev \
            libxss-dev \
            libgl1-mesa-dev \
            libgles2-mesa-dev \
            libegl1-mesa-dev \
            libglu1-mesa-dev
            
          # Ubuntu 22.04 specific compatibility packages
          sudo apt-get install -y libtinfo6 || echo "libtinfo6 not available"
          sudo apt-get install -y libncurses6 || echo "libncurses6 not available"

          # Fix any broken dependencies
          sudo apt-get --fix-broken install -y || echo "No broken dependencies to fix"

          # Verify key packages are installed
          echo "Verifying key packages..."
          dpkg -l | grep -E "(libsdl2|libgstreamer|libgl1-mesa|libgles2-mesa)" || echo "Some packages may not be installed"

          # Check Java installation
          echo "Checking Java installation..."
          java -version || echo "Java not found"
          javac -version || echo "Java compiler not found"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install --upgrade virtualenv
          pip install buildozer==1.5.0
          pip install python-for-android==2024.1.21
          pip install pillow requests

          # Verify installations
          echo "Verifying Python packages..."
          python -c "import buildozer; print(f'Buildozer version: {buildozer.__version__}')"
          python -c "import p4a; print(f'Python-for-Android version: {p4a.__version__}')" || echo "p4a module not found, checking alternative import"
          python -c "import pythonforandroid; print('python-for-android imported successfully')" || echo "python-for-android import failed"

          # List installed packages
          pip list | grep -E "(buildozer|python-for-android|virtualenv)"

      - name: Setup Android SDK
        run: |
          # Create Android SDK directory
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform

          # Download and setup Android SDK
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q commandlinetools-linux-8512546_latest.zip
          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest

          # Create the old tools directory structure that Buildozer expects
          mkdir -p android-sdk/tools/bin
          ln -sf $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

          # Set environment variables
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

          # Accept licenses
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

          # Install required SDK packages
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3" "ndk;21.4.7075529"

          # Verify installation
          ls -la $ANDROID_HOME/build-tools/
          ls -la $ANDROID_HOME/platform-tools/
          ls -la $ANDROID_HOME/tools/bin/

      - name: Configure environment
        run: |
          # Set environment variables
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PYTHONPATH=$PYTHONPATH:$HOME/.local/lib/python3.10/site-packages
          export PATH=$PATH:$HOME/.local/bin

          # Verify environment
          echo "ANDROID_HOME: $ANDROID_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          echo "PATH: $PATH"
          echo "PYTHONPATH: $PYTHONPATH"

          # Test key tools
          java -version
          javac -version
          python --version
          buildozer --version

      - name: Initialize Buildozer
        run: |
          # Set environment variables
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PYTHONPATH=$PYTHONPATH:$HOME/.local/lib/python3.10/site-packages
          export PATH=$PATH:$HOME/.local/bin

          # Initialize buildozer
          buildozer init || echo "Buildozer already initialized"

          # Create .buildozer directory if it doesn't exist
          mkdir -p .buildozer

          # Set proper permissions
          chmod -R 755 .buildozer || echo "Permission setting failed"

      - name: Build with Buildozer
        run: |
          # Set environment variables for the build
          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/30.0.3
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PYTHONPATH=$PYTHONPATH:$HOME/.local/lib/python3.10/site-packages
          export PATH=$PATH:$HOME/.local/bin

          # Clean previous builds if they exist
          buildozer android clean || echo "No previous builds to clean"

          # Build the APK with verbose output
          buildozer android debug -v
        env:
          JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
          ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk

      - name: List build artifacts
        run: |
          ls -la bin/ || echo "No bin directory found"
          find . -name "*.apk" -type f || echo "No APK files found"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
        if: hashFiles('bin/*.apk') != ''

      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
