name: Build Android APK

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Cache buildozer global directory
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache buildozer directory
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          # Fix for libtinfo5 on newer Ubuntu
          sudo apt-get install -y libtinfo5 || sudo apt-get install -y libncurses5
          # Install additional dependencies for buildozer
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33
          pip install kivy==2.1.0 kivymd==1.1.1 pillow requests

      - name: Initialize Buildozer
        run: |
          buildozer init || echo "Buildozer already initialized"

      - name: Build with Buildozer
        run: |
          buildozer android debug
        env:
          JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

      - name: List build artifacts
        run: |
          ls -la bin/ || echo "No bin directory found"
          find . -name "*.apk" -type f || echo "No APK files found"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
        if: hashFiles('bin/*.apk') != ''

      - name: Create Release (if tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
